#!/bin/bash

list=("bulbasaur" "ivysaur" "venusaur" "charmander" "charmeleon")
url="https://pokeapi.co/api/v2/pokemon/"

echo "Error Log - $(date)" > "error.log"

for mixed_case_pokemon in "${list[@]}"; do
    pokemon=${mixed_case_pokemon,,}
    curl -X GET "$url$pokemon" -s -o "$pokemon.json" -w "%{http_code}" > "$pokemon".txt
    http_code=$(cat "$pokemon".txt)

    if [ "$http_code" -eq 200 ]; then
        echo "API request successful. Data saved to $pokemon.json"
    else
        echo " $(date): API request to $url$pokemon failed with status code $http_code" >> "error.log"
    fi

    sleep 5
done

if ls *.txt 1> /dev/null 2>&1; then
    rm *.txt
else
    echo "No .txt files found to remove."
fi
